import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { JetBrains_Mono, Laila } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import Header from "@/components/ui/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

const laila = Laila({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-jetbrainsMono",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <ClerkProvider>
        <body
          className={`${laila.className} bg-[#FAF9F6]`}
          style={{
            backgroundImage: "url(/5.jpg)",
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            backgroundPosition: "center center",
            minHeight: "100vh",
            minWidth: "100vw",
            height: "100%",
            width: "100%",
            margin: 0,
            padding: 0,
            overflow: "hidden",
          }}
        >
          <Header />
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
